apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"helloworld-demo","release":"V76"},"name":"helloworld","namespace":"default"},"spec":{"containers":[{"image":"denniszielke/aci-helloworld:latest","name":"aci-helloworld","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"200m","memory":"128Mi"}}}]}}
  creationTimestamp: "2020-01-27T10:49:23Z"
  labels:
    app: helloworld-demo
    release: V76
  name: helloworld
  namespace: default
  resourceVersion: "11769"
  selfLink: /api/v1/namespaces/default/pods/helloworld
  uid: 4d3040d4-2069-4027-a6e7-48ebedf965f8
spec:
  containers:
  - image: denniszielke/aci-helloworld:latest
    imagePullPolicy: Always
    name: aci-helloworld
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-pmrt8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-default-23914282-vmss000001
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-pmrt8
    secret:
      defaultMode: 420
      secretName: default-token-pmrt8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-27T10:49:23Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-27T10:49:33Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-27T10:49:33Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-27T10:49:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a48406ffd244376bb383fe17176f16e845fc845476777ee38d5a77185c285056
    image: denniszielke/aci-helloworld:latest
    imageID: docker-pullable://denniszielke/aci-helloworld@sha256:324104a853600a595fd1dc5b6471a0c0163342996848a1231f3b4b1cbe9a8464
    lastState: {}
    name: aci-helloworld
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-01-27T10:49:33Z"
  hostIP: 10.0.5.35
  phase: Running
  podIP: 10.0.5.61
  qosClass: Burstable
  startTime: "2020-01-27T10:49:23Z"
